[package]
name = "cpp-to-rust"
version = "0.1.0"
authors = ["timmonfette1 <monfette.timothy@gmail.com>"]

[lib]
name = "double_input"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
